# Generated by Django 6.0.2 on 2026-02-26 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='integration_poll_duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600), help_text="Durée par défaut des scrutins d'intégration/bannissement (ex: 01:00:00 pour 1 heure)"),
        ),
    ]
