# Generated by Django 6.0.3 on 2026-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
        ('users', '0003_user_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house',
        ),
        migrations.AddField(
            model_name='user',
            name='houses',
            field=models.ManyToManyField(blank=True, related_name='members', to='houses.house'),
        ),
    ]
