upstream django_app {
    server web:8000;
}

server {
    listen 80;
    server_name localhost fairpoll.org www.fairpoll.org;

    # Docker's internal DNS resolver
    resolver 127.0.0.11 valid=10s;

    location / {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
    }

    location /static/ {
        alias /app/staticfiles/;
    }

    location /media/ {
        alias /app/media/;
    }
}
