# Generated by Django 6.0.3 on 2026-03-26 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('houses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HousePoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('dead_line', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('is_ticket_secured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(default=list)),
                ('poll_type', models.CharField(choices=[('governance', 'Governance Poll'), ('custom', 'Custom Poll'), ('banishment', 'Banishment'), ('integration', 'Integration'), ('deletion', 'Deletion')], default='custom', max_length=20)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_polls', to=settings.AUTH_USER_MODEL)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='houses.house')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuickPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('dead_line', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField()),
                ('is_ticket_secured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('options', models.JSONField(default=list)),
                ('poll_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='polls.housepoll')),
            ],
            options={
                'unique_together': {('poll', 'code')},
            },
        ),
        migrations.CreateModel(
            name='QuickBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.quickpoll')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quick_ballots', to='polls.ticket')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='polls.housepoll')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.ticket')),
            ],
        ),
        migrations.CreateModel(
            name='BallotChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_index', models.PositiveIntegerField()),
                ('rank', models.PositiveIntegerField()),
                ('house_ballot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.houseballot')),
                ('quick_ballot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='polls.quickballot')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('house_ballot__isnull', False)), fields=('house_ballot', 'option_index'), name='unique_option_per_house_ballot'), models.UniqueConstraint(condition=models.Q(('quick_ballot__isnull', False)), fields=('quick_ballot', 'option_index'), name='unique_option_per_quick_ballot'), models.UniqueConstraint(condition=models.Q(('house_ballot__isnull', False)), fields=('house_ballot', 'rank'), name='unique_rank_per_house_ballot'), models.UniqueConstraint(condition=models.Q(('quick_ballot__isnull', False)), fields=('quick_ballot', 'rank'), name='unique_rank_per_quick_ballot')],
            },
        ),
        migrations.AddConstraint(
            model_name='houseballot',
            constraint=models.UniqueConstraint(condition=models.Q(('voter__isnull', False)), fields=('poll', 'voter'), name='unique_voter_per_house_poll'),
        ),
        migrations.AddConstraint(
            model_name='houseballot',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket__isnull', False)), fields=('poll', 'ticket'), name='unique_ticket_per_house_poll'),
        ),
    ]
