# Generated by Django 6.0.3 on 2026-03-08 09:45

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quickpoll',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quickpoll',
            name='participants_voted_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quickpoll',
            name='poll_id',
            field=models.CharField(default=polls.models.generate_quickpoll_id, editable=False, max_length=6, unique=True),
        ),
    ]
