# Generated by Django 5.2.11 on 2026-03-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepoll',
            name='options',
            field=models.JSONField(default=list, help_text='List of choices for the poll.'),
        ),
        migrations.AddField(
            model_name='quickpoll',
            name='options',
            field=models.JSONField(default=list, help_text='List of choices for the poll.'),
        ),
    ]
