# Generated by Django 6.0.3 on 2026-03-08 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_quickpoll_duration_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickPollProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField()),
                ('quickpoll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions', to='polls.quickpoll')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('quickpoll', 'position')},
            },
        ),
    ]
