# Generated by Django 6.0.2 on 2026-02-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_pollsecretkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='choice',
        ),
        migrations.AddField(
            model_name='vote',
            name='choices_order',
            field=models.JSONField(blank=True, help_text='Liste ordonnée des ID de Choice', null=True),
        ),
    ]
