# Generated by Django 6.0.3 on 2026-03-26 14:17

import polls.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_housepoll_options_quickpoll_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickpoll',
            name='external_id',
            field=models.CharField(default=polls.models.generate_ticket_code, editable=False, max_length=8, unique=True),
        ),
    ]
