# Generated by Django 6.0.2 on 2026-02-26 12:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_vote_choice_vote_choices_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='use_tickets',
            field=models.BooleanField(default=True, verbose_name='Sécurisation par ticket'),
        ),
        migrations.AddField(
            model_name='poll',
            name='voters',
            field=models.ManyToManyField(blank=True, related_name='voted_ticketless_polls', to=settings.AUTH_USER_MODEL),
        ),
    ]
