# Generated by Django 5.2.11 on 2026-03-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_polllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepoll',
            name='ballot_count_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quickpoll',
            name='ballot_count_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
