# Generated by Django 5.2.11 on 2026-04-09 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_housepoll_ballot_count_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housepoll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quickpoll',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
