# Generated by Django 5.2.11 on 2026-05-03 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('polls', '0007_housepoll_created_at_quickpoll_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polllog',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='polllog',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
